### ISSUE TITLE
No English repository description

### ISSUE THREAD

**Issue by vi** [geeeeeeeeek/WeChatLuckyMoney#6]
It's not clear what is this project about, yet it appears in Github's "Trending repositories".

In addition to current description, there should also be a short English description.

**Comment by geeeeeeeeek** [comment]
Well, it does have an English README. Have you read that, this is an Android app that helps you snatch virtual red envelopes in WeChat group chat. 

Since WeChat is mostly used in China, I havent add support for other system languages. But thanks for your advice, English support and short description will come soon.
